// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Mobile   string `json:"mobile" validate:"required,email"`
	Password string `json:"password" validate:"required,password"`
}

type RegisterResq struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type TestReq struct {
	Id int64 `json:"id" validate:"required,gte=0"`
}

type TestResp struct {
	Info string `json:"info"`
}

type UserLoginReq struct {
	Mobile   string `json:"mobile" validate:"required,email"`
	Password string `json:"password" validate:"required,password"`
}

type UserLoginResq struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}
